"""Updated OperatorState table

Revision ID: 06528bca5156
Revises: c1a0a02c3498
Create Date: 2025-11-16 23:05:22.482924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06528bca5156'
down_revision: Union[str, Sequence[str], None] = 'c1a0a02c3498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator_state', 'metadata_fetched_at')
    op.drop_column('operator_state', 'metadata_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_state', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('operator_state', sa.Column('metadata_fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
