"""Updated operators table

Revision ID: 52e74ddbb6b4
Revises: d309d4871f58
Create Date: 2025-11-16 22:03:31.937823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e74ddbb6b4'
down_revision: Union[str, Sequence[str], None] = 'd309d4871f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_delegation_approver_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('old_delegation_approver', sa.String(), nullable=True),
    sa.Column('new_delegation_approver', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_at_block', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delegation_approver_hist_operator', 'operator_delegation_approver_history', ['operator_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_operator_delegation_approver_history_changed_at'), 'operator_delegation_approver_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_operator_delegation_approver_history_operator_id'), 'operator_delegation_approver_history', ['operator_id'], unique=False)
    op.create_table('operator_metadata',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('metadata_uri', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_block', sa.Integer(), nullable=False),
    sa.Column('total_updates', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_index('idx_operator_metadata_updated', 'operator_metadata', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_operator_metadata_operator_id'), 'operator_metadata', ['operator_id'], unique=False)
    op.create_table('operator_metadata_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('metadata_uri', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metadata_history_block', 'operator_metadata_history', ['updated_at_block'], unique=False)
    op.create_index('idx_metadata_history_operator', 'operator_metadata_history', ['operator_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_operator_metadata_history_operator_id'), 'operator_metadata_history', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_metadata_history_updated_at'), 'operator_metadata_history', ['updated_at'], unique=False)
    op.create_table('operator_registration',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('registration_block', sa.Integer(), nullable=False),
    sa.Column('delegation_approver', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_index('idx_operator_registration_block', 'operator_registration', ['registration_block'], unique=False)
    op.create_index('idx_operator_registration_date', 'operator_registration', ['registered_at'], unique=False)
    op.create_index(op.f('ix_operator_registration_operator_id'), 'operator_registration', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_registration_operator_id'), table_name='operator_registration')
    op.drop_index('idx_operator_registration_date', table_name='operator_registration')
    op.drop_index('idx_operator_registration_block', table_name='operator_registration')
    op.drop_table('operator_registration')
    op.drop_index(op.f('ix_operator_metadata_history_updated_at'), table_name='operator_metadata_history')
    op.drop_index(op.f('ix_operator_metadata_history_operator_id'), table_name='operator_metadata_history')
    op.drop_index('idx_metadata_history_operator', table_name='operator_metadata_history')
    op.drop_index('idx_metadata_history_block', table_name='operator_metadata_history')
    op.drop_table('operator_metadata_history')
    op.drop_index(op.f('ix_operator_metadata_operator_id'), table_name='operator_metadata')
    op.drop_index('idx_operator_metadata_updated', table_name='operator_metadata')
    op.drop_table('operator_metadata')
    op.drop_index(op.f('ix_operator_delegation_approver_history_operator_id'), table_name='operator_delegation_approver_history')
    op.drop_index(op.f('ix_operator_delegation_approver_history_changed_at'), table_name='operator_delegation_approver_history')
    op.drop_index('idx_delegation_approver_hist_operator', table_name='operator_delegation_approver_history')
    op.drop_table('operator_delegation_approver_history')
    # ### end Alembic commands ###
