"""Fixed unique constratin bug in snapshot tables

Revision ID: 64f6578abd61
Revises: e9d3174fcb76
Create Date: 2025-11-16 12:23:25.434498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f6578abd61'
down_revision: Union[str, Sequence[str], None] = 'e9d3174fcb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('operator_daily_snapshots_operator_date_key', 'operator_daily_snapshots', ['operator_id', 'snapshot_date'])
    op.create_unique_constraint('operator_strategy_daily_snapshots_operator_strategy_date_key', 'operator_strategy_daily_snapshots', ['operator_id', 'strategy_id', 'snapshot_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operator_strategy_daily_snapshots_operator_strategy_date_key', 'operator_strategy_daily_snapshots', type_='unique')
    op.drop_constraint('operator_daily_snapshots_operator_date_key', 'operator_daily_snapshots', type_='unique')
    # ### end Alembic commands ###
