"""initial schema 4

Revision ID: 722be0bbfe2b
Revises: a578ba8c1a87
Create Date: 2025-11-15 06:08:58.991262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722be0bbfe2b'
down_revision: Union[str, Sequence[str], None] = 'a578ba8c1a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('operators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('pipeline_checkpoints',
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(), nullable=False),
    sa.Column('last_processed_block', sa.BigInteger(), nullable=True),
    sa.Column('operators_processed_count', sa.Integer(), nullable=True),
    sa.Column('total_events_processed', sa.Integer(), nullable=True),
    sa.Column('run_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_name')
    )
    op.create_table('stakers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('concentration_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('concentration_type', sa.String(), nullable=False),
    sa.Column('hhi_value', sa.Numeric(), nullable=True),
    sa.Column('gini_coefficient', sa.Numeric(), nullable=True),
    sa.Column('coefficient_of_variation', sa.Numeric(), nullable=True),
    sa.Column('top_1_percentage', sa.Numeric(), nullable=True),
    sa.Column('top_5_percentage', sa.Numeric(), nullable=True),
    sa.Column('top_10_percentage', sa.Numeric(), nullable=True),
    sa.Column('total_entities', sa.Integer(), nullable=True),
    sa.Column('effective_entities', sa.Numeric(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', 'concentration_type', name='uix_concentration_metrics')
    )
    op.create_index('idx_concentration_entity', 'concentration_metrics', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index(op.f('ix_concentration_metrics_concentration_type'), 'concentration_metrics', ['concentration_type'], unique=False)
    op.create_index(op.f('ix_concentration_metrics_date'), 'concentration_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_concentration_metrics_entity_id'), 'concentration_metrics', ['entity_id'], unique=False)
    op.create_index(op.f('ix_concentration_metrics_entity_type'), 'concentration_metrics', ['entity_type'], unique=False)
    op.create_table('operator_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Numeric(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('performance_score', sa.Numeric(), nullable=True),
    sa.Column('economic_score', sa.Numeric(), nullable=True),
    sa.Column('network_position_score', sa.Numeric(), nullable=True),
    sa.Column('delegation_hhi', sa.Numeric(), nullable=True),
    sa.Column('delegation_volatility_7d', sa.Numeric(), nullable=True),
    sa.Column('delegation_volatility_30d', sa.Numeric(), nullable=True),
    sa.Column('delegation_volatility_90d', sa.Numeric(), nullable=True),
    sa.Column('growth_rate_30d', sa.Numeric(), nullable=True),
    sa.Column('growth_consistency_score', sa.Numeric(), nullable=True),
    sa.Column('size_percentile', sa.Numeric(), nullable=True),
    sa.Column('delegator_distribution_cv', sa.Numeric(), nullable=True),
    sa.Column('snapshot_total_delegated_shares', sa.Numeric(), nullable=True),
    sa.Column('snapshot_delegator_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_avs_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_commission_bips', sa.Numeric(), nullable=True),
    sa.Column('slashing_event_count', sa.Integer(), nullable=True),
    sa.Column('lifetime_slashing_amount', sa.Numeric(), nullable=True),
    sa.Column('operational_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_sufficient_data', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operator_analytics_date_risk', 'operator_analytics', ['date', 'risk_score'], unique=False)
    op.create_index('idx_operator_analytics_operator_date', 'operator_analytics', ['operator_id', 'date'], unique=False)
    op.create_index(op.f('ix_operator_analytics_date'), 'operator_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_operator_analytics_operator_id'), 'operator_analytics', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_analytics_risk_level'), 'operator_analytics', ['risk_level'], unique=False)
    op.create_table('operator_avs_allocation_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('total_allocated_magnitude', sa.Numeric(), nullable=True),
    sa.Column('active_allocation_count', sa.Integer(), nullable=True),
    sa.Column('last_allocated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_avs_alloc_summary_avs', 'operator_avs_allocation_summary', ['avs_id'], unique=False)
    op.create_index('idx_avs_alloc_summary_magnitude', 'operator_avs_allocation_summary', ['total_allocated_magnitude'], unique=False)
    op.create_index('idx_avs_alloc_summary_operator', 'operator_avs_allocation_summary', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_allocation_summary_avs_id'), 'operator_avs_allocation_summary', ['avs_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_allocation_summary_operator_id'), 'operator_avs_allocation_summary', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_allocation_summary_strategy_id'), 'operator_avs_allocation_summary', ['strategy_id'], unique=False)
    op.create_table('operator_avs_registration_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=False),
    sa.Column('status_changed_block', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_avs_reg_hist_avs', 'operator_avs_registration_history', ['avs_id', 'status_changed_at'], unique=False)
    op.create_index('idx_avs_reg_hist_operator', 'operator_avs_registration_history', ['operator_id', 'status_changed_at'], unique=False)
    op.create_index('idx_avs_reg_hist_period', 'operator_avs_registration_history', ['operator_id', 'avs_id'], unique=False)
    op.create_index('idx_avs_reg_hist_status', 'operator_avs_registration_history', ['status'], unique=False)
    op.create_index(op.f('ix_operator_avs_registration_history_avs_id'), 'operator_avs_registration_history', ['avs_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_registration_history_operator_id'), 'operator_avs_registration_history', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_registration_history_status_changed_at'), 'operator_avs_registration_history', ['status_changed_at'], unique=False)
    op.create_table('operator_avs_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('current_status_since', sa.DateTime(), nullable=False),
    sa.Column('first_registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_unregistered_at', sa.DateTime(), nullable=True),
    sa.Column('total_registration_cycles', sa.Integer(), nullable=True),
    sa.Column('total_days_registered', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_days', sa.Integer(), nullable=True),
    sa.Column('active_operator_set_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_operator_set_count', sa.Integer(), nullable=True),
    sa.Column('avs_commission_bips', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_avs_rel_cycles', 'operator_avs_relationships', ['total_registration_cycles'], unique=False)
    op.create_index('idx_avs_rel_operator_status', 'operator_avs_relationships', ['operator_id', 'current_status'], unique=False)
    op.create_index('idx_avs_rel_status', 'operator_avs_relationships', ['current_status'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationships_avs_id'), 'operator_avs_relationships', ['avs_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationships_current_status'), 'operator_avs_relationships', ['current_status'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationships_operator_id'), 'operator_avs_relationships', ['operator_id'], unique=False)
    op.create_table('operator_daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('delegator_count', sa.Integer(), nullable=True),
    sa.Column('active_avs_count', sa.Integer(), nullable=True),
    sa.Column('active_operator_set_count', sa.Integer(), nullable=True),
    sa.Column('pi_split_bips', sa.Integer(), nullable=True),
    sa.Column('slash_event_count_to_date', sa.Integer(), nullable=True),
    sa.Column('operational_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_date', 'operator_daily_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshot_operator_date', 'operator_daily_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_daily_snapshots_operator_id'), 'operator_daily_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_daily_snapshots_snapshot_date'), 'operator_daily_snapshots', ['snapshot_date'], unique=False)
    op.create_table('operator_delegator_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('delegation_type', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_block', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delegator_hist_operator', 'operator_delegator_history', ['operator_id', 'event_timestamp'], unique=False)
    op.create_index('idx_delegator_hist_staker', 'operator_delegator_history', ['staker_id', 'event_timestamp'], unique=False)
    op.create_index('idx_delegator_hist_type', 'operator_delegator_history', ['delegation_type'], unique=False)
    op.create_index(op.f('ix_operator_delegator_history_event_timestamp'), 'operator_delegator_history', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_operator_delegator_history_operator_id'), 'operator_delegator_history', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_history_staker_id'), 'operator_delegator_history', ['staker_id'], unique=False)
    op.create_table('operator_delegator_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(), nullable=False),
    sa.Column('shares_updated_at', sa.DateTime(), nullable=True),
    sa.Column('shares_updated_block', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delegator_shares_amount', 'operator_delegator_shares', ['shares'], unique=False)
    op.create_index('idx_delegator_shares_operator', 'operator_delegator_shares', ['operator_id'], unique=False)
    op.create_index('idx_delegator_shares_staker', 'operator_delegator_shares', ['staker_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_operator_id'), 'operator_delegator_shares', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_staker_id'), 'operator_delegator_shares', ['staker_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_strategy_id'), 'operator_delegator_shares', ['strategy_id'], unique=False)
    op.create_table('operator_delegators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('is_delegated', sa.Boolean(), nullable=True),
    sa.Column('delegated_at', sa.DateTime(), nullable=False),
    sa.Column('undelegated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delegator_operator_status', 'operator_delegators', ['operator_id', 'is_delegated'], unique=False)
    op.create_index(op.f('ix_operator_delegators_is_delegated'), 'operator_delegators', ['is_delegated'], unique=False)
    op.create_index(op.f('ix_operator_delegators_operator_id'), 'operator_delegators', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_delegators_staker_id'), 'operator_delegators', ['staker_id'], unique=False)
    op.create_table('operator_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operator_set_avs', 'operator_sets', ['avs_id'], unique=False)
    op.create_index(op.f('ix_operator_sets_avs_id'), 'operator_sets', ['avs_id'], unique=False)
    op.create_table('operator_state',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_address', sa.String(), nullable=False),
    sa.Column('current_metadata_uri', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('registration_block', sa.Integer(), nullable=True),
    sa.Column('first_activity_at', sa.DateTime(), nullable=False),
    sa.Column('first_activity_block', sa.Integer(), nullable=False),
    sa.Column('first_activity_type', sa.String(), nullable=True),
    sa.Column('current_delegation_approver', sa.String(), nullable=False),
    sa.Column('is_permissioned', sa.Boolean(), nullable=True),
    sa.Column('delegation_approver_updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_pi_split_bips', sa.Integer(), nullable=True),
    sa.Column('pi_split_activated_at', sa.DateTime(), nullable=True),
    sa.Column('active_avs_count', sa.Integer(), nullable=True),
    sa.Column('active_operator_set_count', sa.Integer(), nullable=True),
    sa.Column('registered_avs_count', sa.Integer(), nullable=True),
    sa.Column('total_delegators', sa.Integer(), nullable=True),
    sa.Column('active_delegators', sa.Integer(), nullable=True),
    sa.Column('total_slash_events', sa.Integer(), nullable=True),
    sa.Column('last_slashed_at', sa.DateTime(), nullable=True),
    sa.Column('force_undelegation_count', sa.Integer(), nullable=True),
    sa.Column('last_allocation_at', sa.DateTime(), nullable=True),
    sa.Column('last_commission_change_at', sa.DateTime(), nullable=True),
    sa.Column('last_metadata_update_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('operational_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id'),
    sa.UniqueConstraint('operator_address')
    )
    op.create_index('idx_operator_active', 'operator_state', ['is_active'], unique=False)
    op.create_index('idx_operator_first_activity', 'operator_state', ['first_activity_at'], unique=False)
    op.create_index('idx_operator_slashes', 'operator_state', ['total_slash_events'], unique=False)
    op.create_index(op.f('ix_operator_state_operator_id'), 'operator_state', ['operator_id'], unique=False)
    op.create_table('operator_strategy_daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('max_magnitude', sa.Numeric(), nullable=False),
    sa.Column('encumbered_magnitude', sa.Numeric(), nullable=True),
    sa.Column('utilization_rate', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_snapshot_magnitude', 'operator_strategy_daily_snapshots', ['max_magnitude'], unique=False)
    op.create_index('idx_strategy_snapshot_operator_date', 'operator_strategy_daily_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index('idx_strategy_snapshot_strategy_date', 'operator_strategy_daily_snapshots', ['strategy_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_strategy_daily_snapshots_operator_id'), 'operator_strategy_daily_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_strategy_daily_snapshots_snapshot_date'), 'operator_strategy_daily_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_strategy_daily_snapshots_strategy_id'), 'operator_strategy_daily_snapshots', ['strategy_id'], unique=False)
    op.create_table('operator_strategy_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('max_magnitude', sa.Numeric(), nullable=False),
    sa.Column('max_magnitude_updated_at', sa.DateTime(), nullable=True),
    sa.Column('max_magnitude_updated_block', sa.Integer(), nullable=True),
    sa.Column('encumbered_magnitude', sa.Numeric(), nullable=False),
    sa.Column('encumbered_magnitude_updated_at', sa.DateTime(), nullable=True),
    sa.Column('encumbered_magnitude_updated_block', sa.Integer(), nullable=True),
    sa.Column('utilization_rate', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operator_strategy_max_mag', 'operator_strategy_state', ['max_magnitude'], unique=False)
    op.create_index('idx_operator_strategy_operator', 'operator_strategy_state', ['operator_id'], unique=False)
    op.create_index('idx_operator_strategy_utilization', 'operator_strategy_state', ['utilization_rate'], unique=False)
    op.create_index(op.f('ix_operator_strategy_state_operator_id'), 'operator_strategy_state', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_strategy_state_strategy_id'), 'operator_strategy_state', ['strategy_id'], unique=False)
    op.create_table('volatility_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('volatility_7d', sa.Numeric(), nullable=True),
    sa.Column('volatility_30d', sa.Numeric(), nullable=True),
    sa.Column('volatility_90d', sa.Numeric(), nullable=True),
    sa.Column('mean_value', sa.Numeric(), nullable=True),
    sa.Column('coefficient_of_variation', sa.Numeric(), nullable=True),
    sa.Column('trend_direction', sa.Numeric(), nullable=True),
    sa.Column('trend_strength', sa.Numeric(), nullable=True),
    sa.Column('data_points_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', 'metric_type', name='uix_volatility_metrics')
    )
    op.create_index('idx_volatility_entity', 'volatility_metrics', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index(op.f('ix_volatility_metrics_date'), 'volatility_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_volatility_metrics_entity_id'), 'volatility_metrics', ['entity_id'], unique=False)
    op.create_index(op.f('ix_volatility_metrics_entity_type'), 'volatility_metrics', ['entity_type'], unique=False)
    op.create_index(op.f('ix_volatility_metrics_metric_type'), 'volatility_metrics', ['metric_type'], unique=False)
    op.create_table('operator_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Numeric(), nullable=False),
    sa.Column('effect_block', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('allocated_at_block', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allocation_effect', 'operator_allocations', ['effect_block'], unique=False)
    op.create_index('idx_allocation_operator', 'operator_allocations', ['operator_id'], unique=False)
    op.create_index('idx_allocation_operator_avs', 'operator_allocations', ['operator_id', 'operator_set_id'], unique=False)
    op.create_index('idx_allocation_status', 'operator_allocations', ['is_active'], unique=False)
    op.create_index(op.f('ix_operator_allocations_is_active'), 'operator_allocations', ['is_active'], unique=False)
    op.create_index(op.f('ix_operator_allocations_operator_id'), 'operator_allocations', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_allocations_operator_set_id'), 'operator_allocations', ['operator_set_id'], unique=False)
    op.create_index(op.f('ix_operator_allocations_strategy_id'), 'operator_allocations', ['strategy_id'], unique=False)
    op.create_table('operator_commission_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('commission_type', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=True),
    sa.Column('operator_set_id', sa.String(), nullable=True),
    sa.Column('old_bips', sa.Integer(), nullable=False),
    sa.Column('new_bips', sa.Integer(), nullable=False),
    sa.Column('change_delta', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('activation_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('caller', sa.String(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commission_hist_operator', 'operator_commission_history', ['operator_id', 'changed_at'], unique=False)
    op.create_index('idx_commission_hist_type', 'operator_commission_history', ['commission_type'], unique=False)
    op.create_index(op.f('ix_operator_commission_history_changed_at'), 'operator_commission_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_operator_commission_history_commission_type'), 'operator_commission_history', ['commission_type'], unique=False)
    op.create_index(op.f('ix_operator_commission_history_operator_id'), 'operator_commission_history', ['operator_id'], unique=False)
    op.create_table('operator_commission_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('commission_type', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=True),
    sa.Column('operator_set_id', sa.String(), nullable=True),
    sa.Column('current_bips', sa.Integer(), nullable=False),
    sa.Column('current_activated_at', sa.DateTime(), nullable=False),
    sa.Column('current_set_at_block', sa.Integer(), nullable=False),
    sa.Column('upcoming_bips', sa.Integer(), nullable=True),
    sa.Column('upcoming_activated_at', sa.DateTime(), nullable=True),
    sa.Column('upcoming_set_at_block', sa.Integer(), nullable=True),
    sa.Column('previous_bips', sa.Integer(), nullable=True),
    sa.Column('total_changes', sa.Integer(), nullable=True),
    sa.Column('first_set_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commission_avs', 'operator_commission_rates', ['operator_id', 'avs_id'], unique=False)
    op.create_index('idx_commission_bips', 'operator_commission_rates', ['current_bips'], unique=False)
    op.create_index('idx_commission_operator', 'operator_commission_rates', ['operator_id'], unique=False)
    op.create_index('idx_commission_type', 'operator_commission_rates', ['commission_type'], unique=False)
    op.create_index(op.f('ix_operator_commission_rates_operator_id'), 'operator_commission_rates', ['operator_id'], unique=False)
    op.create_table('operator_slashing_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('slashed_at', sa.DateTime(), nullable=False),
    sa.Column('slashed_at_block', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slash_avs', 'operator_slashing_incidents', ['operator_set_id'], unique=False)
    op.create_index('idx_slash_operator_date', 'operator_slashing_incidents', ['operator_id', 'slashed_at'], unique=False)
    op.create_index(op.f('ix_operator_slashing_incidents_operator_id'), 'operator_slashing_incidents', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_slashing_incidents_slashed_at'), 'operator_slashing_incidents', ['slashed_at'], unique=False)
    op.create_table('operator_slashing_amounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slashing_incident_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('wad_slashed', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slashing_incident_id'], ['operator_slashing_incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slash_amount_incident', 'operator_slashing_amounts', ['slashing_incident_id'], unique=False)
    op.create_index('idx_slash_amount_operator', 'operator_slashing_amounts', ['operator_id'], unique=False)
    op.create_index('idx_slash_amount_strategy', 'operator_slashing_amounts', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_operator_slashing_amounts_operator_id'), 'operator_slashing_amounts', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_slashing_amounts_slashing_incident_id'), 'operator_slashing_amounts', ['slashing_incident_id'], unique=False)
    op.create_index(op.f('ix_operator_slashing_amounts_strategy_id'), 'operator_slashing_amounts', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_slashing_amounts_strategy_id'), table_name='operator_slashing_amounts')
    op.drop_index(op.f('ix_operator_slashing_amounts_slashing_incident_id'), table_name='operator_slashing_amounts')
    op.drop_index(op.f('ix_operator_slashing_amounts_operator_id'), table_name='operator_slashing_amounts')
    op.drop_index('idx_slash_amount_strategy', table_name='operator_slashing_amounts')
    op.drop_index('idx_slash_amount_operator', table_name='operator_slashing_amounts')
    op.drop_index('idx_slash_amount_incident', table_name='operator_slashing_amounts')
    op.drop_table('operator_slashing_amounts')
    op.drop_index(op.f('ix_operator_slashing_incidents_slashed_at'), table_name='operator_slashing_incidents')
    op.drop_index(op.f('ix_operator_slashing_incidents_operator_id'), table_name='operator_slashing_incidents')
    op.drop_index('idx_slash_operator_date', table_name='operator_slashing_incidents')
    op.drop_index('idx_slash_avs', table_name='operator_slashing_incidents')
    op.drop_table('operator_slashing_incidents')
    op.drop_index(op.f('ix_operator_commission_rates_operator_id'), table_name='operator_commission_rates')
    op.drop_index('idx_commission_type', table_name='operator_commission_rates')
    op.drop_index('idx_commission_operator', table_name='operator_commission_rates')
    op.drop_index('idx_commission_bips', table_name='operator_commission_rates')
    op.drop_index('idx_commission_avs', table_name='operator_commission_rates')
    op.drop_table('operator_commission_rates')
    op.drop_index(op.f('ix_operator_commission_history_operator_id'), table_name='operator_commission_history')
    op.drop_index(op.f('ix_operator_commission_history_commission_type'), table_name='operator_commission_history')
    op.drop_index(op.f('ix_operator_commission_history_changed_at'), table_name='operator_commission_history')
    op.drop_index('idx_commission_hist_type', table_name='operator_commission_history')
    op.drop_index('idx_commission_hist_operator', table_name='operator_commission_history')
    op.drop_table('operator_commission_history')
    op.drop_index(op.f('ix_operator_allocations_strategy_id'), table_name='operator_allocations')
    op.drop_index(op.f('ix_operator_allocations_operator_set_id'), table_name='operator_allocations')
    op.drop_index(op.f('ix_operator_allocations_operator_id'), table_name='operator_allocations')
    op.drop_index(op.f('ix_operator_allocations_is_active'), table_name='operator_allocations')
    op.drop_index('idx_allocation_status', table_name='operator_allocations')
    op.drop_index('idx_allocation_operator_avs', table_name='operator_allocations')
    op.drop_index('idx_allocation_operator', table_name='operator_allocations')
    op.drop_index('idx_allocation_effect', table_name='operator_allocations')
    op.drop_table('operator_allocations')
    op.drop_index(op.f('ix_volatility_metrics_metric_type'), table_name='volatility_metrics')
    op.drop_index(op.f('ix_volatility_metrics_entity_type'), table_name='volatility_metrics')
    op.drop_index(op.f('ix_volatility_metrics_entity_id'), table_name='volatility_metrics')
    op.drop_index(op.f('ix_volatility_metrics_date'), table_name='volatility_metrics')
    op.drop_index('idx_volatility_entity', table_name='volatility_metrics')
    op.drop_table('volatility_metrics')
    op.drop_index(op.f('ix_operator_strategy_state_strategy_id'), table_name='operator_strategy_state')
    op.drop_index(op.f('ix_operator_strategy_state_operator_id'), table_name='operator_strategy_state')
    op.drop_index('idx_operator_strategy_utilization', table_name='operator_strategy_state')
    op.drop_index('idx_operator_strategy_operator', table_name='operator_strategy_state')
    op.drop_index('idx_operator_strategy_max_mag', table_name='operator_strategy_state')
    op.drop_table('operator_strategy_state')
    op.drop_index(op.f('ix_operator_strategy_daily_snapshots_strategy_id'), table_name='operator_strategy_daily_snapshots')
    op.drop_index(op.f('ix_operator_strategy_daily_snapshots_snapshot_date'), table_name='operator_strategy_daily_snapshots')
    op.drop_index(op.f('ix_operator_strategy_daily_snapshots_operator_id'), table_name='operator_strategy_daily_snapshots')
    op.drop_index('idx_strategy_snapshot_strategy_date', table_name='operator_strategy_daily_snapshots')
    op.drop_index('idx_strategy_snapshot_operator_date', table_name='operator_strategy_daily_snapshots')
    op.drop_index('idx_strategy_snapshot_magnitude', table_name='operator_strategy_daily_snapshots')
    op.drop_table('operator_strategy_daily_snapshots')
    op.drop_index(op.f('ix_operator_state_operator_id'), table_name='operator_state')
    op.drop_index('idx_operator_slashes', table_name='operator_state')
    op.drop_index('idx_operator_first_activity', table_name='operator_state')
    op.drop_index('idx_operator_active', table_name='operator_state')
    op.drop_table('operator_state')
    op.drop_index(op.f('ix_operator_sets_avs_id'), table_name='operator_sets')
    op.drop_index('idx_operator_set_avs', table_name='operator_sets')
    op.drop_table('operator_sets')
    op.drop_index(op.f('ix_operator_delegators_staker_id'), table_name='operator_delegators')
    op.drop_index(op.f('ix_operator_delegators_operator_id'), table_name='operator_delegators')
    op.drop_index(op.f('ix_operator_delegators_is_delegated'), table_name='operator_delegators')
    op.drop_index('idx_delegator_operator_status', table_name='operator_delegators')
    op.drop_table('operator_delegators')
    op.drop_index(op.f('ix_operator_delegator_shares_strategy_id'), table_name='operator_delegator_shares')
    op.drop_index(op.f('ix_operator_delegator_shares_staker_id'), table_name='operator_delegator_shares')
    op.drop_index(op.f('ix_operator_delegator_shares_operator_id'), table_name='operator_delegator_shares')
    op.drop_index('idx_delegator_shares_staker', table_name='operator_delegator_shares')
    op.drop_index('idx_delegator_shares_operator', table_name='operator_delegator_shares')
    op.drop_index('idx_delegator_shares_amount', table_name='operator_delegator_shares')
    op.drop_table('operator_delegator_shares')
    op.drop_index(op.f('ix_operator_delegator_history_staker_id'), table_name='operator_delegator_history')
    op.drop_index(op.f('ix_operator_delegator_history_operator_id'), table_name='operator_delegator_history')
    op.drop_index(op.f('ix_operator_delegator_history_event_timestamp'), table_name='operator_delegator_history')
    op.drop_index('idx_delegator_hist_type', table_name='operator_delegator_history')
    op.drop_index('idx_delegator_hist_staker', table_name='operator_delegator_history')
    op.drop_index('idx_delegator_hist_operator', table_name='operator_delegator_history')
    op.drop_table('operator_delegator_history')
    op.drop_index(op.f('ix_operator_daily_snapshots_snapshot_date'), table_name='operator_daily_snapshots')
    op.drop_index(op.f('ix_operator_daily_snapshots_operator_id'), table_name='operator_daily_snapshots')
    op.drop_index('idx_snapshot_operator_date', table_name='operator_daily_snapshots')
    op.drop_index('idx_snapshot_date', table_name='operator_daily_snapshots')
    op.drop_table('operator_daily_snapshots')
    op.drop_index(op.f('ix_operator_avs_relationships_operator_id'), table_name='operator_avs_relationships')
    op.drop_index(op.f('ix_operator_avs_relationships_current_status'), table_name='operator_avs_relationships')
    op.drop_index(op.f('ix_operator_avs_relationships_avs_id'), table_name='operator_avs_relationships')
    op.drop_index('idx_avs_rel_status', table_name='operator_avs_relationships')
    op.drop_index('idx_avs_rel_operator_status', table_name='operator_avs_relationships')
    op.drop_index('idx_avs_rel_cycles', table_name='operator_avs_relationships')
    op.drop_table('operator_avs_relationships')
    op.drop_index(op.f('ix_operator_avs_registration_history_status_changed_at'), table_name='operator_avs_registration_history')
    op.drop_index(op.f('ix_operator_avs_registration_history_operator_id'), table_name='operator_avs_registration_history')
    op.drop_index(op.f('ix_operator_avs_registration_history_avs_id'), table_name='operator_avs_registration_history')
    op.drop_index('idx_avs_reg_hist_status', table_name='operator_avs_registration_history')
    op.drop_index('idx_avs_reg_hist_period', table_name='operator_avs_registration_history')
    op.drop_index('idx_avs_reg_hist_operator', table_name='operator_avs_registration_history')
    op.drop_index('idx_avs_reg_hist_avs', table_name='operator_avs_registration_history')
    op.drop_table('operator_avs_registration_history')
    op.drop_index(op.f('ix_operator_avs_allocation_summary_strategy_id'), table_name='operator_avs_allocation_summary')
    op.drop_index(op.f('ix_operator_avs_allocation_summary_operator_id'), table_name='operator_avs_allocation_summary')
    op.drop_index(op.f('ix_operator_avs_allocation_summary_avs_id'), table_name='operator_avs_allocation_summary')
    op.drop_index('idx_avs_alloc_summary_operator', table_name='operator_avs_allocation_summary')
    op.drop_index('idx_avs_alloc_summary_magnitude', table_name='operator_avs_allocation_summary')
    op.drop_index('idx_avs_alloc_summary_avs', table_name='operator_avs_allocation_summary')
    op.drop_table('operator_avs_allocation_summary')
    op.drop_index(op.f('ix_operator_analytics_risk_level'), table_name='operator_analytics')
    op.drop_index(op.f('ix_operator_analytics_operator_id'), table_name='operator_analytics')
    op.drop_index(op.f('ix_operator_analytics_date'), table_name='operator_analytics')
    op.drop_index('idx_operator_analytics_operator_date', table_name='operator_analytics')
    op.drop_index('idx_operator_analytics_date_risk', table_name='operator_analytics')
    op.drop_table('operator_analytics')
    op.drop_index(op.f('ix_concentration_metrics_entity_type'), table_name='concentration_metrics')
    op.drop_index(op.f('ix_concentration_metrics_entity_id'), table_name='concentration_metrics')
    op.drop_index(op.f('ix_concentration_metrics_date'), table_name='concentration_metrics')
    op.drop_index(op.f('ix_concentration_metrics_concentration_type'), table_name='concentration_metrics')
    op.drop_index('idx_concentration_entity', table_name='concentration_metrics')
    op.drop_table('concentration_metrics')
    op.drop_table('strategies')
    op.drop_table('stakers')
    op.drop_table('pipeline_checkpoints')
    op.drop_table('operators')
    op.drop_table('avs')
    # ### end Alembic commands ###
