"""Remove is_active and activated_at from operator_allocations

Revision ID: 8dd39eebf771
Revises: 722be0bbfe2b
Create Date: 2025-11-15 18:50:49.442539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd39eebf771'
down_revision: Union[str, Sequence[str], None] = '722be0bbfe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avs', 'name')
    op.drop_index(op.f('idx_allocation_status'), table_name='operator_allocations')
    op.drop_index(op.f('ix_operator_allocations_is_active'), table_name='operator_allocations')
    op.drop_column('operator_allocations', 'activated_at')
    op.drop_column('operator_allocations', 'is_active')
    op.drop_column('strategies', 'symbol')
    op.drop_column('strategies', 'decimals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('decimals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('operator_allocations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('operator_allocations', sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_operator_allocations_is_active'), 'operator_allocations', ['is_active'], unique=False)
    op.create_index(op.f('idx_allocation_status'), 'operator_allocations', ['is_active'], unique=False)
    op.add_column('avs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
