"""Updated OperatorState table

Revision ID: c1a0a02c3498
Revises: 116e01d7b638
Create Date: 2025-11-16 23:03:10.830375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a0a02c3498'
down_revision: Union[str, Sequence[str], None] = '116e01d7b638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operator_state', 'first_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('operator_state', 'first_activity_block',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operator_state', 'first_activity_block',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('operator_state', 'first_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
