"""added slashing events cache table

Revision ID: e9d3174fcb76
Revises: 325970da8e31
Create Date: 2025-11-15 20:48:02.721276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d3174fcb76'
down_revision: Union[str, Sequence[str], None] = '325970da8e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slashing_events_cache',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('slashed_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('strategies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('wad_slashed', sa.ARRAY(sa.Numeric()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('operator_id', 'block_number', 'transaction_hash')
    )
    op.create_index('idx_slashing_cache_operator', 'slashing_events_cache', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_slashing_cache_operator', table_name='slashing_events_cache')
    op.drop_table('slashing_events_cache')
    # ### end Alembic commands ###
