"""Change some BigIntegers to Numeric

Revision ID: 414ba4028ceb
Revises: 6c87c90c274e
Create Date: 2025-11-02 18:30:43.417091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '414ba4028ceb'
down_revision: Union[str, Sequence[str], None] = '6c87c90c274e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allocation_events', 'magnitude',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('beacon_chain_deposit_events', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('beacon_chain_eth_withdrawal_completed_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('beacon_chain_slashing_events', 'prev_beacon_chain_slashing_factor',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('beacon_chain_slashing_events', 'new_beacon_chain_slashing_factor',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('beacon_chain_withdrawal_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('burn_or_redistributable_shares_decreased_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('burn_or_redistributable_shares_increased_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('burnable_eth_shares_increased_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('deposit_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('deposit_scaling_factor_updated_events', 'new_deposit_scaling_factor',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('distribution_root_disabled_events', 'root_index',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('distribution_root_submitted_events', 'root_index',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('encumbered_magnitude_updated_events', 'encumbered_magnitude',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('max_magnitude_updated_events', 'max_magnitude',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_avs_split_bips_set_events', 'old_operator_avs_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_avs_split_bips_set_events', 'new_operator_avs_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_pi_split_bips_set_events', 'old_operator_pi_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_pi_split_bips_set_events', 'new_operator_pi_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_set_split_bips_set_events', 'old_operator_set_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_set_split_bips_set_events', 'new_operator_set_split_bips',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_share_events', 'shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_shares_slashed_events', 'total_slashed_shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('operator_slashed_events', 'wad_slashed',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.Numeric()),
               existing_nullable=False)
    op.alter_column('pectra_fork_timestamp_set_events', 'new_pectra_fork_timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('pod_shares_update_events', 'shares_delta',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('pod_shares_update_events', 'new_total_shares',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('rewards_claimed_events', 'claimed_amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('rewards_submission_events', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('withdrawal_events', 'shares',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.Numeric()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawal_events', 'shares',
               existing_type=postgresql.ARRAY(sa.Numeric()),
               type_=postgresql.ARRAY(sa.BIGINT()),
               existing_nullable=False)
    op.alter_column('rewards_submission_events', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('rewards_claimed_events', 'claimed_amount',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('pod_shares_update_events', 'new_total_shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('pod_shares_update_events', 'shares_delta',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('pectra_fork_timestamp_set_events', 'new_pectra_fork_timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_slashed_events', 'wad_slashed',
               existing_type=postgresql.ARRAY(sa.Numeric()),
               type_=postgresql.ARRAY(sa.BIGINT()),
               existing_nullable=False)
    op.alter_column('operator_shares_slashed_events', 'total_slashed_shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_share_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_set_split_bips_set_events', 'new_operator_set_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_set_split_bips_set_events', 'old_operator_set_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_pi_split_bips_set_events', 'new_operator_pi_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_pi_split_bips_set_events', 'old_operator_pi_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_avs_split_bips_set_events', 'new_operator_avs_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('operator_avs_split_bips_set_events', 'old_operator_avs_split_bips',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('max_magnitude_updated_events', 'max_magnitude',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('encumbered_magnitude_updated_events', 'encumbered_magnitude',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('distribution_root_submitted_events', 'root_index',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('distribution_root_disabled_events', 'root_index',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('deposit_scaling_factor_updated_events', 'new_deposit_scaling_factor',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('deposit_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('burnable_eth_shares_increased_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('burn_or_redistributable_shares_increased_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('burn_or_redistributable_shares_decreased_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('beacon_chain_withdrawal_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('beacon_chain_slashing_events', 'new_beacon_chain_slashing_factor',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('beacon_chain_slashing_events', 'prev_beacon_chain_slashing_factor',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('beacon_chain_eth_withdrawal_completed_events', 'shares',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('beacon_chain_deposit_events', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('allocation_events', 'magnitude',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
