"""init

Revision ID: 0f7b366697fc
Revises: 
Create Date: 2025-09-15 08:52:30.060444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7b366697fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concentration_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('concentration_type', sa.String(length=20), nullable=False),
    sa.Column('hhi_value', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('gini_coefficient', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('coefficient_of_variation', sa.Numeric(), nullable=True),
    sa.Column('top_1_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_5_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_10_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_entities', sa.Integer(), nullable=True),
    sa.Column('effective_entities', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('operator_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', 'concentration_type', name='uix_concentration_metrics')
    )
    op.create_table('operator_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('economic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('network_position_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delegation_hhi', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('delegation_volatility_7d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('delegation_volatility_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('delegation_volatility_90d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('growth_rate_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('growth_consistency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('size_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delegator_distribution_cv', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('snapshot_total_delegated_shares', sa.Numeric(), nullable=True),
    sa.Column('snapshot_delegator_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_avs_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_commission_bips', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('slashing_event_count', sa.Integer(), nullable=True),
    sa.Column('lifetime_slashing_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('operational_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_sufficient_data', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'date', name='uix_operator_analytics')
    )
    op.create_index('idx_operator_analytics_date_active', 'operator_analytics', ['date', 'is_active'], unique=False)
    op.create_index('idx_operator_analytics_date_risk', 'operator_analytics', ['date', 'risk_score'], unique=False)
    op.create_table('volatility_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=20), nullable=False),
    sa.Column('volatility_7d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volatility_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volatility_90d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mean_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('coefficient_of_variation', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trend_direction', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trend_strength', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('data_points_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', 'metric_type', name='uix_volatility_metrics')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volatility_metrics')
    op.drop_index('idx_operator_analytics_date_risk', table_name='operator_analytics')
    op.drop_index('idx_operator_analytics_date_active', table_name='operator_analytics')
    op.drop_table('operator_analytics')
    op.drop_table('concentration_metrics')
    # ### end Alembic commands ###
