"""Created new snapshot tables

Revision ID: 86220018415e
Revises: 64f6578abd61
Create Date: 2025-11-16 15:55:25.956299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86220018415e'
down_revision: Union[str, Sequence[str], None] = '64f6578abd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_daily_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('total_operators', sa.Integer(), nullable=True),
    sa.Column('active_operators', sa.Integer(), nullable=True),
    sa.Column('total_tvs', sa.Numeric(), nullable=True),
    sa.Column('mean_tvs', sa.Numeric(), nullable=True),
    sa.Column('median_tvs', sa.Numeric(), nullable=True),
    sa.Column('p25_tvs', sa.Numeric(), nullable=True),
    sa.Column('p75_tvs', sa.Numeric(), nullable=True),
    sa.Column('p90_tvs', sa.Numeric(), nullable=True),
    sa.Column('total_delegators', sa.Integer(), nullable=True),
    sa.Column('mean_delegators_per_operator', sa.Numeric(), nullable=True),
    sa.Column('median_delegators_per_operator', sa.Numeric(), nullable=True),
    sa.Column('mean_avs_per_operator', sa.Numeric(), nullable=True),
    sa.Column('median_avs_per_operator', sa.Numeric(), nullable=True),
    sa.Column('mean_pi_commission_bips', sa.Numeric(), nullable=True),
    sa.Column('median_pi_commission_bips', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_network_agg_date', 'network_daily_aggregates', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_network_daily_aggregates_snapshot_date'), 'network_daily_aggregates', ['snapshot_date'], unique=True)
    op.create_table('operator_avs_relationship_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('days_registered_to_date', sa.Integer(), nullable=True),
    sa.Column('current_period_days', sa.Integer(), nullable=True),
    sa.Column('total_registration_cycles', sa.Integer(), nullable=True),
    sa.Column('active_operator_set_count', sa.Integer(), nullable=True),
    sa.Column('avs_commission_bips', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'avs_id', 'snapshot_date', name='operator_avs_relationship_snapshots_unique')
    )
    op.create_index('idx_avs_rel_snap_avs_date', 'operator_avs_relationship_snapshots', ['avs_id', 'snapshot_date'], unique=False)
    op.create_index('idx_avs_rel_snap_operator_date', 'operator_avs_relationship_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index('idx_avs_rel_snap_status', 'operator_avs_relationship_snapshots', ['current_status'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationship_snapshots_avs_id'), 'operator_avs_relationship_snapshots', ['avs_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationship_snapshots_operator_id'), 'operator_avs_relationship_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_avs_relationship_snapshots_snapshot_date'), 'operator_avs_relationship_snapshots', ['snapshot_date'], unique=False)
    op.create_table('operator_delegator_shares_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(), nullable=False),
    sa.Column('is_delegated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'staker_id', 'strategy_id', 'snapshot_date', name='operator_delegator_shares_snapshots_unique')
    )
    op.create_index('idx_delegator_shares_snap_delegated', 'operator_delegator_shares_snapshots', ['is_delegated'], unique=False)
    op.create_index('idx_delegator_shares_snap_operator_date', 'operator_delegator_shares_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index('idx_delegator_shares_snap_staker_date', 'operator_delegator_shares_snapshots', ['staker_id', 'snapshot_date'], unique=False)
    op.create_index('idx_delegator_shares_snap_strategy_date', 'operator_delegator_shares_snapshots', ['strategy_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_snapshots_operator_id'), 'operator_delegator_shares_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_snapshots_snapshot_date'), 'operator_delegator_shares_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_snapshots_staker_id'), 'operator_delegator_shares_snapshots', ['staker_id'], unique=False)
    op.create_index(op.f('ix_operator_delegator_shares_snapshots_strategy_id'), 'operator_delegator_shares_snapshots', ['strategy_id'], unique=False)
    op.create_table('operator_allocation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('magnitude', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'operator_set_id', 'strategy_id', 'snapshot_date', name='operator_allocation_snapshots_unique')
    )
    op.create_index('idx_allocation_snap_operator_date', 'operator_allocation_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index('idx_allocation_snap_operator_set_date', 'operator_allocation_snapshots', ['operator_set_id', 'snapshot_date'], unique=False)
    op.create_index('idx_allocation_snap_strategy_date', 'operator_allocation_snapshots', ['strategy_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_allocation_snapshots_operator_id'), 'operator_allocation_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_allocation_snapshots_operator_set_id'), 'operator_allocation_snapshots', ['operator_set_id'], unique=False)
    op.create_index(op.f('ix_operator_allocation_snapshots_snapshot_date'), 'operator_allocation_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_operator_allocation_snapshots_strategy_id'), 'operator_allocation_snapshots', ['strategy_id'], unique=False)
    op.create_table('operator_commission_rates_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('commission_type', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=True),
    sa.Column('operator_set_id', sa.String(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_block', sa.Integer(), nullable=False),
    sa.Column('current_bips', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'commission_type', 'snapshot_date', name='operator_commission_rates_snapshots_unique')
    )
    op.create_index('idx_commission_snap_avs', 'operator_commission_rates_snapshots', ['avs_id', 'snapshot_date'], unique=False)
    op.create_index('idx_commission_snap_operator_date', 'operator_commission_rates_snapshots', ['operator_id', 'snapshot_date'], unique=False)
    op.create_index('idx_commission_snap_type', 'operator_commission_rates_snapshots', ['commission_type'], unique=False)
    op.create_index(op.f('ix_operator_commission_rates_snapshots_commission_type'), 'operator_commission_rates_snapshots', ['commission_type'], unique=False)
    op.create_index(op.f('ix_operator_commission_rates_snapshots_operator_id'), 'operator_commission_rates_snapshots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_commission_rates_snapshots_snapshot_date'), 'operator_commission_rates_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_commission_rates_snapshots_snapshot_date'), table_name='operator_commission_rates_snapshots')
    op.drop_index(op.f('ix_operator_commission_rates_snapshots_operator_id'), table_name='operator_commission_rates_snapshots')
    op.drop_index(op.f('ix_operator_commission_rates_snapshots_commission_type'), table_name='operator_commission_rates_snapshots')
    op.drop_index('idx_commission_snap_type', table_name='operator_commission_rates_snapshots')
    op.drop_index('idx_commission_snap_operator_date', table_name='operator_commission_rates_snapshots')
    op.drop_index('idx_commission_snap_avs', table_name='operator_commission_rates_snapshots')
    op.drop_table('operator_commission_rates_snapshots')
    op.drop_index(op.f('ix_operator_allocation_snapshots_strategy_id'), table_name='operator_allocation_snapshots')
    op.drop_index(op.f('ix_operator_allocation_snapshots_snapshot_date'), table_name='operator_allocation_snapshots')
    op.drop_index(op.f('ix_operator_allocation_snapshots_operator_set_id'), table_name='operator_allocation_snapshots')
    op.drop_index(op.f('ix_operator_allocation_snapshots_operator_id'), table_name='operator_allocation_snapshots')
    op.drop_index('idx_allocation_snap_strategy_date', table_name='operator_allocation_snapshots')
    op.drop_index('idx_allocation_snap_operator_set_date', table_name='operator_allocation_snapshots')
    op.drop_index('idx_allocation_snap_operator_date', table_name='operator_allocation_snapshots')
    op.drop_table('operator_allocation_snapshots')
    op.drop_index(op.f('ix_operator_delegator_shares_snapshots_strategy_id'), table_name='operator_delegator_shares_snapshots')
    op.drop_index(op.f('ix_operator_delegator_shares_snapshots_staker_id'), table_name='operator_delegator_shares_snapshots')
    op.drop_index(op.f('ix_operator_delegator_shares_snapshots_snapshot_date'), table_name='operator_delegator_shares_snapshots')
    op.drop_index(op.f('ix_operator_delegator_shares_snapshots_operator_id'), table_name='operator_delegator_shares_snapshots')
    op.drop_index('idx_delegator_shares_snap_strategy_date', table_name='operator_delegator_shares_snapshots')
    op.drop_index('idx_delegator_shares_snap_staker_date', table_name='operator_delegator_shares_snapshots')
    op.drop_index('idx_delegator_shares_snap_operator_date', table_name='operator_delegator_shares_snapshots')
    op.drop_index('idx_delegator_shares_snap_delegated', table_name='operator_delegator_shares_snapshots')
    op.drop_table('operator_delegator_shares_snapshots')
    op.drop_index(op.f('ix_operator_avs_relationship_snapshots_snapshot_date'), table_name='operator_avs_relationship_snapshots')
    op.drop_index(op.f('ix_operator_avs_relationship_snapshots_operator_id'), table_name='operator_avs_relationship_snapshots')
    op.drop_index(op.f('ix_operator_avs_relationship_snapshots_avs_id'), table_name='operator_avs_relationship_snapshots')
    op.drop_index('idx_avs_rel_snap_status', table_name='operator_avs_relationship_snapshots')
    op.drop_index('idx_avs_rel_snap_operator_date', table_name='operator_avs_relationship_snapshots')
    op.drop_index('idx_avs_rel_snap_avs_date', table_name='operator_avs_relationship_snapshots')
    op.drop_table('operator_avs_relationship_snapshots')
    op.drop_index(op.f('ix_network_daily_aggregates_snapshot_date'), table_name='network_daily_aggregates')
    op.drop_index('idx_network_agg_date', table_name='network_daily_aggregates')
    op.drop_table('network_daily_aggregates')
    # ### end Alembic commands ###
