"""Updated operator analytics table

Revision ID: d309d4871f58
Revises: 963fd5789c0b
Create Date: 2025-11-16 21:18:21.157996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd309d4871f58'
down_revision: Union[str, Sequence[str], None] = '963fd5789c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_operator_analytics_operator_date'), table_name='operator_analytics')
    op.create_unique_constraint('uq_operator_analytics_operator_date', 'operator_analytics', ['operator_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_operator_analytics_operator_date', 'operator_analytics', type_='unique')
    op.create_index(op.f('idx_operator_analytics_operator_date'), 'operator_analytics', ['operator_id', 'date'], unique=False)
    # ### end Alembic commands ###
