"""init

Revision ID: f56af3637dd1
Revises: 0f7b366697fc
Create Date: 2025-09-15 08:56:36.897686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56af3637dd1'
down_revision: Union[str, Sequence[str], None] = '0f7b366697fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_operator_analytics'), 'operator_analytics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_operator_analytics'), 'operator_analytics', ['operator_id', 'date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
